name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add upstream and sync
        run: |
          git remote add upstream https://github.com/lbc-team/Pioneer.git
          git fetch upstream
          git checkout master
          git merge upstream/master --allow-unrelated-histories
          git push origin master
